language: python
python:
  - "3.6"      # current default Python on Travis CI
before_install:
  # so that I could call conda install
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - python --version
  - pip install -U pip
  - pip install -U pytest
install:
  - pip install -r requirements.txt
  - pip install -e .
  - conda install GDAL=2.3.3
  - "curl -L 'https://github.com/libspatialindex/libspatialindex/archive/1.8.5.tar.gz' | tar -xz"
  - cd libspatialindex-1.8.5 && ./autogen.sh && ./configure && make && make install && ldconfig
script:
  - pytest
