input:
    dataPath: 'data/'
    trainFile: 'train.tif'
    testFile: 'test.tif'
    truthFile: 'train_ground_truth.shp'
output:
  plotdir: 'plotField/'
  MLplotdir: 'plotML/'
ML:
  logreg: True
  SVM: False
  RFC: False
  trainndvi: True    # should be always true
  trainhue: False     # whether or not to train on Hue image values
  trainendvi: True    # whether or not to train on ENDVI
  traincvi: False    # whether or not to train on CVI
  trainng: False    # whether or not to train on NG
  trainnnir: False
  trainnr: False
  traintvi: False
misc:
  saveFig: True
  verbose: False
