input:
    dataPath: 'data/'
    trainFile: 'train.tif'
    testFile: 'test.tif'
    truthFile: 'train_ground_truth.shp'
output:
  plotdir: 'plotField/'
  MLplotdir: 'plotML/'
misc:
  saveFig: True
  verbose: False
  trainndvi: True    # should be always true
  trainhue: True     # whether or not to train on Hue image values
  trainendvi: True    # whether or not to train on ENDVI
  traincvi: True    # whether or not to train on CVI
  trainng: True    # whether or not to train on NG
  trainnnir: True
  trainnr: True
  traintvi: True